import { Platform, StatusBar, StyleSheet } from 'react-native';
import { COLORS } from './colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.card },
  screen: { flex: 1, backgroundColor: COLORS.card },
  scroll: { flex: 1, paddingHorizontal: 16 },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight ? StatusBar.currentHeight + 8 : 34) : 12,
    paddingBottom: 10,
    backgroundColor: COLORS.card,
  },
  brandTopBar: {
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight ? StatusBar.currentHeight + 8 : 34) : 12,
    paddingBottom: 12,
    backgroundColor: COLORS.card,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  avatarBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F472B6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEmoji: { fontSize: 18 },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.line,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  iconGlyph: { fontSize: 16, color: COLORS.ink },
  headerTitle: { fontWeight: '700', fontSize: 16.5, color: COLORS.ink },
  headerSub: { fontSize: 11.5, color: COLORS.inkSoft, marginTop: 1 },
  badge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 17,
    height: 17,
    borderRadius: 8.5,
    backgroundColor: COLORS.green,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.card,
  },
  badgeText: { fontSize: 9, fontWeight: '800', color: '#FFFFFF' },

  locationPill: { marginBottom: 12, flexDirection: 'row', alignItems: 'center', gap: 4 },
  locationText: { color: COLORS.greenDark, fontWeight: '700', fontSize: 12.5 },

  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.bg,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    marginBottom: 14,
  },
  searchInput: { flex: 1, fontSize: 13.5, color: COLORS.ink },

  chipRow: { marginBottom: 12 },
  trendLabel: { color: COLORS.inkSoft, fontSize: 11.5, alignSelf: 'center', marginRight: 4 },
  chip: {
    backgroundColor: COLORS.greenPale,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 20,
    paddingHorizontal: 13,
    paddingVertical: 7,
    marginRight: 8,
  },
  chipActive: { backgroundColor: COLORS.green, borderColor: COLORS.green },
  chipText: { fontSize: 11.5, fontWeight: '600', color: COLORS.ink },
  chipTextActive: { color: '#fff' },

  offerCard: {
    backgroundColor: COLORS.greenLight,
    borderWidth: 1,
    borderColor: COLORS.greenBorder,
    borderRadius: 18,
    padding: 14,
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  offerCardTag: {
    fontSize: 10,
    fontWeight: '800',
    color: COLORS.greenDark,
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  offerCardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.ink,
    marginBottom: 2,
  },
  offerCardSub: {
    fontSize: 11,
    color: COLORS.inkSoft,
    maxWidth: 200,
  },
  offerCardBtn: {
    backgroundColor: COLORS.green,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerCardBtnText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 12,
    letterSpacing: 0.5,
  },

  sectionTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 4 },
  sectionTitle: { fontWeight: '700', fontSize: 14.5, color: COLORS.ink, marginBottom: 10 },
  sectionSub: { fontSize: 11, color: COLORS.inkSoft, marginBottom: 10 },
  linkText: { fontSize: 11.5, fontWeight: '700', color: COLORS.greenDark },

  reorderCard: {
    width: 172,
    backgroundColor: COLORS.bg,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 16,
    padding: 12,
    marginRight: 10,
    justifyContent: 'space-between',
  },
  reorderTitle: { fontSize: 12, fontWeight: '700', marginBottom: 2, color: COLORS.ink },
  reorderSub: { fontSize: 10.5, color: COLORS.inkSoft, marginBottom: 10, minHeight: 28 },
  againBtn: { backgroundColor: COLORS.green, borderRadius: 9, paddingVertical: 7, alignItems: 'center' },
  againBtnText: { color: '#fff', fontWeight: '700', fontSize: 11 },

  pcard: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 16,
    padding: 11,
    minHeight: 284,
    justifyContent: 'space-between',
    flexDirection: 'column',
    position: 'relative',
  },
  pcardImg: {
    width: '100%',
    height: 88,
    borderRadius: 10,
    backgroundColor: COLORS.bg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    overflow: 'hidden',
  },
  pcardPhoto: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  pcardName: { fontSize: 12.5, fontWeight: '700', color: COLORS.ink, minHeight: 34, lineHeight: 17 },
  pcardMeta: { fontSize: 10.5, color: COLORS.inkSoft, minHeight: 16 },
  pcardPriceRow: { flexDirection: 'row', gap: 6, alignItems: 'baseline', minHeight: 20, marginTop: 4, marginBottom: 2 },
  pcardStrike: { fontSize: 10.5, color: COLORS.inkSoft, textDecorationLine: 'line-through' },
  pcardPct: { fontSize: 10.5, color: COLORS.greenDark, fontWeight: '700' },
  pcardFinal: { fontSize: 14.5, fontWeight: '800', color: COLORS.ink, marginBottom: 8 },
  rxTag: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: COLORS.amberLight,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
    zIndex: 2,
  },
  rxTagText: { fontSize: 8.5, fontWeight: '800', color: '#8a5c0a' },

  addBtn: {
    borderWidth: 1.4,
    borderRadius: 8,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtnText: { fontWeight: '800', fontSize: 11.5, letterSpacing: 0.3 },
  qtyStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 8,
    height: 36,
    paddingHorizontal: 12,
  },
  qtyStepperBtn: { color: '#fff', fontWeight: '800', fontSize: 15 },
  qtyStepperVal: { color: '#fff', fontWeight: '800', fontSize: 12 },

  grid2: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 14,
    paddingBottom: 16,
  },

  subTag: { backgroundColor: COLORS.purpleLight, borderRadius: 8, paddingVertical: 4, marginTop: 6, alignItems: 'center' },
  subTagText: { color: COLORS.purple, fontSize: 9, fontWeight: '700' },

  groupCard: { backgroundColor: COLORS.greenLight, borderRadius: 20, padding: 14, marginBottom: 18 },
  groupCardTitle: { fontWeight: '700', fontSize: 15, color: COLORS.ink, marginBottom: 12 },
  groupGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 10,
    marginBottom: 12,
  },
  groupTile: {
    width: '30.9%',
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 8,
    borderWidth: 1,
    borderColor: COLORS.line,
    minHeight: 128,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  groupTileName: {
    fontSize: 10.5,
    fontWeight: '700',
    color: COLORS.ink,
    textAlign: 'center',
    minHeight: 28,
    lineHeight: 14,
  },
  groupTileDiscount: {
    fontSize: 9.5,
    color: COLORS.greenDark,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 4,
  },
  groupTileImg: {
    width: '100%',
    height: 48,
    borderRadius: 8,
    backgroundColor: COLORS.bg,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  groupTilePhoto: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
  },
  viewAllText: { color: COLORS.greenDark, fontWeight: '700', fontSize: 12.5 },

  cartBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.green,
    borderRadius: 16,
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 10,
  },
  cartBarLine: { color: '#fff', fontWeight: '700', fontSize: 13 },
  cartBarSub: { color: '#fff', opacity: 0.85, fontSize: 10.5 },
  cartBarBtn: { backgroundColor: '#fff', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8 },
  cartBarBtnText: { color: COLORS.greenDark, fontWeight: '800', fontSize: 12 },

  promoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.greenLight,
    marginHorizontal: 16,
    marginBottom: 10,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  promoText: { color: COLORS.greenDark, fontWeight: '700', fontSize: 12 },
  promoBtn: { backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.green, borderRadius: 9, paddingHorizontal: 14, paddingVertical: 6 },
  promoBtnText: { color: COLORS.greenDark, fontWeight: '800', fontSize: 11 },

  bottomNav: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    paddingTop: 8,
    paddingBottom: Platform.OS === 'ios' ? 22 : 10,
    backgroundColor: COLORS.card,
  },
  bnItem: { flex: 1, alignItems: 'center', gap: 3 },
  bnIcon: { fontSize: 16 },
  bnLabel: { fontSize: 9, fontWeight: '700', color: COLORS.inkSoft },
  bnLabelActive: { color: COLORS.greenDark },

  subtabStrip: { paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: COLORS.line, flexGrow: 0 },
  subtab: { alignItems: 'center', width: 62, marginRight: 16 },
  subtabAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.bg,
    borderWidth: 2,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  subtabAvatarActive: { borderColor: COLORS.green, backgroundColor: COLORS.greenLight },
  subtabLabel: { fontSize: 9.5, fontWeight: '700', color: COLORS.inkSoft, textAlign: 'center' },
  subtabLabelActive: { color: COLORS.greenDark },

  filterRow: { alignItems: 'flex-end', marginBottom: 12, marginTop: 4 },
  filterChip: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 20,
    paddingHorizontal: 13,
    paddingVertical: 7,
  },
  filterChipText: { fontSize: 11.5, fontWeight: '700', color: COLORS.ink },

  pdHero: { width: '100%', height: 180, borderRadius: 16, backgroundColor: COLORS.bg, alignItems: 'center', justifyContent: 'center', marginBottom: 14, overflow: 'hidden' },
  pdHeroPhoto: { width: '100%', height: '100%', borderRadius: 16 },
  pdRxTag: { color: '#8a5c0a', fontWeight: '800', fontSize: 11, marginBottom: 6 },
  pdName: { fontSize: 17, fontWeight: '700', color: COLORS.ink, marginBottom: 2 },
  pdGeneric: { fontSize: 12, color: COLORS.inkSoft, marginBottom: 10 },
  pdPriceRow: { flexDirection: 'row', gap: 8, alignItems: 'baseline', marginBottom: 14 },
  pdPrice: { fontSize: 20, fontWeight: '800', color: COLORS.ink },
  pdDesc: { fontSize: 12.5, color: COLORS.inkSoft, lineHeight: 20, marginBottom: 18 },

  similarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 13,
    padding: 10,
    marginBottom: 9,
  },
  similarImg: { width: 40, height: 40, borderRadius: 10, backgroundColor: COLORS.bg, alignItems: 'center', justifyContent: 'center' },
  similarName: { fontSize: 12, fontWeight: '700', color: COLORS.ink },
  similarMeta: { fontSize: 10.5, color: COLORS.inkSoft },

  bottomDock: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 24 : 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    backgroundColor: COLORS.card,
  },
  dockSplit: { flexDirection: 'row', gap: 10, alignItems: 'center' },
  primaryBtn: { backgroundColor: COLORS.green, borderRadius: 14, paddingVertical: 14, alignItems: 'center' },
  primaryBtnText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  primaryBtnDisabled: { backgroundColor: COLORS.line },
  primaryBtnTextDisabled: { color: COLORS.inkSoft },
  warnNote: { fontSize: 11, color: '#B9832A', textAlign: 'center', marginTop: 8 },

  qtyStepperLg: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: COLORS.greenPale,
    borderWidth: 1,
    borderColor: COLORS.green,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  qtyStepperLgBtn: { color: COLORS.greenDark, fontWeight: '800', fontSize: 16 },
  qtyStepperLgVal: { color: COLORS.greenDark, fontWeight: '800', fontSize: 14 },

  emptyCart: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 40 },
  emptyCartText: { fontSize: 13, color: COLORS.inkSoft, marginBottom: 16 },

  cartItem: { flexDirection: 'row', gap: 11, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: COLORS.line },
  ciThumb: { width: 52, height: 52, borderRadius: 12, backgroundColor: COLORS.bg, alignItems: 'center', justifyContent: 'center' },
  ciName: { fontSize: 13, fontWeight: '700', color: COLORS.ink, marginBottom: 2 },
  ciMeta: { fontSize: 10.5, color: COLORS.inkSoft, marginBottom: 8 },
  ciBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  ciPrice: { fontWeight: '800', fontSize: 13, color: COLORS.ink },

  rxUpload: {
    backgroundColor: COLORS.amberLight,
    borderWidth: 1.5,
    borderColor: '#D9A94A',
    borderStyle: 'dashed',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    marginVertical: 16,
  },
  rxUploadDone: { backgroundColor: COLORS.greenLight, borderColor: COLORS.green },
  rxIcon: { fontSize: 26, marginBottom: 6 },
  rxTitle: { fontSize: 13, fontWeight: '700', color: '#6E4A0F', marginBottom: 3 },
  rxSub: { fontSize: 11, color: '#8A6423', marginBottom: 12, textAlign: 'center' },
  rxUploadBtn: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#D9A94A', borderRadius: 9, paddingHorizontal: 16, paddingVertical: 8 },
  rxUploadBtnText: { color: '#8A6423', fontWeight: '700', fontSize: 11.5 },

  summaryLine: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6 },
  summaryLineTotal: { borderTopWidth: 1, borderTopColor: COLORS.line, marginTop: 6, paddingTop: 12 },
  summaryText: { fontSize: 12.5, color: COLORS.inkSoft },
  summaryTotalText: { fontSize: 14, fontWeight: '800', color: COLORS.ink },

  field: { marginBottom: 13 },
  fieldLabel: { fontSize: 11.5, fontWeight: '700', color: COLORS.inkSoft, marginBottom: 6 },
  fieldInput: {
    borderWidth: 1,
    borderColor: COLORS.line,
    backgroundColor: COLORS.bg,
    borderRadius: 11,
    paddingHorizontal: 13,
    paddingVertical: 11,
    fontSize: 13,
    color: COLORS.ink,
  },

  payOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 13,
    padding: 13,
    marginBottom: 9,
  },
  payOptionSelected: { borderColor: COLORS.green, backgroundColor: COLORS.greenPale },
  payLabel: { fontSize: 12.5, fontWeight: '700', color: COLORS.ink },
  paySub: { fontSize: 10.5, color: COLORS.inkSoft },
  radioDot: { width: 18, height: 18, borderRadius: 9, borderWidth: 2, borderColor: COLORS.line },
  radioDotSelected: { borderColor: COLORS.green, backgroundColor: COLORS.green },

  confirmHero: { alignItems: 'center', paddingVertical: 20 },
  confirmCheck: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: COLORS.greenLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  confirmTitle: { fontSize: 17, fontWeight: '700', color: COLORS.ink, marginBottom: 4 },
  confirmSub: { fontSize: 12, color: COLORS.inkSoft },

  etaCard: {
    backgroundColor: COLORS.green,
    borderRadius: 16,
    padding: 16,
    marginVertical: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  etaTitle: { color: '#fff', fontSize: 15, fontWeight: '700' },
  etaSub: { color: '#fff', opacity: 0.85, fontSize: 10.5 },
  etaBadge: { backgroundColor: 'rgba(255,255,255,0.18)', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, alignItems: 'center' },
  etaBadgeNum: { color: '#fff', fontSize: 16, fontWeight: '800' },
  etaBadgeLabel: { color: '#fff', opacity: 0.85, fontSize: 9 },

  orderIdRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
    marginBottom: 6,
  },

  helpRow: { flexDirection: 'row', gap: 10, marginTop: 16 },
  helpBtn: { flex: 1, borderWidth: 1, borderColor: COLORS.line, borderRadius: 12, paddingVertical: 11, alignItems: 'center' },
  helpBtnText: { fontSize: 11.5, fontWeight: '700', color: COLORS.ink },

  toast: {
    position: 'absolute',
    bottom: 26,
    alignSelf: 'center',
    backgroundColor: COLORS.ink,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
  },
  toastText: { color: '#fff', fontSize: 12.5, fontWeight: '600' },

  // ---- Orders Screen Styles ----
  orderCard: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
  },
  orderCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  orderIdText: {
    fontSize: 13.5,
    fontWeight: '800',
    color: COLORS.ink,
  },
  orderDateText: {
    fontSize: 11,
    color: COLORS.inkSoft,
    marginTop: 1,
  },
  statusBadge: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusBadgeDelivered: {
    backgroundColor: COLORS.greenLight,
  },
  statusBadgeDeliveredText: {
    color: COLORS.greenDark,
    fontSize: 10.5,
    fontWeight: '800',
  },
  statusBadgeTransit: {
    backgroundColor: COLORS.amberLight,
  },
  statusBadgeTransitText: {
    color: '#8A5C0A',
    fontSize: 10.5,
    fontWeight: '800',
  },
  orderItemSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 5,
  },
  orderItemName: {
    flex: 1,
    fontSize: 12.5,
    fontWeight: '600',
    color: COLORS.ink,
  },
  orderItemPrice: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.inkSoft,
  },
  orderTotalLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
  },
  orderTotalLabel: {
    fontSize: 12.5,
    color: COLORS.inkSoft,
    fontWeight: '600',
  },
  orderTotalAmount: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.ink,
  },
  orderCardBtns: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  orderBtnReorder: {
    flex: 1,
    backgroundColor: COLORS.green,
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
  },
  orderBtnReorderText: {
    color: '#fff',
    fontSize: 11.5,
    fontWeight: '800',
  },
  orderBtnTrack: {
    flex: 1,
    backgroundColor: COLORS.greenPale,
    borderWidth: 1,
    borderColor: COLORS.greenLight,
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
  },
  orderBtnTrackText: {
    color: COLORS.greenDark,
    fontSize: 11.5,
    fontWeight: '800',
  },

  // ---- Empty Orders State ----
  emptyOrdersContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingVertical: 60,
  },
  emptyOrdersIconCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: COLORS.greenLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  emptyOrdersTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.ink,
    marginBottom: 6,
  },
  emptyOrdersSub: {
    fontSize: 13,
    color: COLORS.inkSoft,
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: 26,
  },
  emptyOrdersBtn: {
    backgroundColor: COLORS.green,
    borderRadius: 14,
    paddingHorizontal: 28,
    paddingVertical: 13,
    alignItems: 'center',
    shadowColor: COLORS.green,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 3,
  },
  emptyOrdersBtnText: {
    color: '#fff',
    fontSize: 13.5,
    fontWeight: '800',
  },
  emptyOrdersDemoBtn: {
    marginTop: 14,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  emptyOrdersDemoText: {
    color: COLORS.greenDark,
    fontSize: 12,
    fontWeight: '700',
  },

  // ---- Account Screen Styles ----
  profileCard: {
    backgroundColor: COLORS.greenLight,
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 16,
  },
  profileAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '900',
  },
  profileName: {
    fontSize: 17,
    fontWeight: '800',
    color: COLORS.ink,
  },
  profilePhone: {
    fontSize: 12,
    color: COLORS.inkSoft,
    marginTop: 2,
  },
  profileBadge: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: COLORS.green,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    alignSelf: 'flex-start',
    marginTop: 5,
  },
  profileBadgeText: {
    color: COLORS.greenDark,
    fontSize: 9.5,
    fontWeight: '800',
  },
  profileEditBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: COLORS.green,
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  profileEditBtnText: {
    color: COLORS.greenDark,
    fontSize: 11,
    fontWeight: '800',
  },
  profileEditInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 13,
    color: COLORS.ink,
    fontWeight: '600',
  },
  profileSaveBtn: {
    backgroundColor: COLORS.green,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 6,
    alignItems: 'center',
  },
  profileSaveBtnText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '800',
  },
  profileCancelBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: 'center',
  },
  profileCancelBtnText: {
    color: COLORS.inkSoft,
    fontSize: 11.5,
    fontWeight: '700',
  },
  accountStats: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  accountStatBox: {
    flex: 1,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 14,
    padding: 12,
    alignItems: 'center',
  },
  accountStatNum: {
    fontSize: 17,
    fontWeight: '800',
    color: COLORS.greenDark,
  },
  accountStatLabel: {
    fontSize: 10.5,
    color: COLORS.inkSoft,
    marginTop: 2,
    fontWeight: '600',
  },
  accountMenuGroup: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 14,
  },
  accountMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  accountMenuIcon: {
    fontSize: 18,
    marginRight: 12,
  },
  accountMenuLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.ink,
  },
  accountMenuSub: {
    fontSize: 11,
    color: COLORS.inkSoft,
    marginRight: 6,
  },
  accountMenuArrow: {
    fontSize: 14,
    color: COLORS.inkSoft,
    fontWeight: '800',
  },
  logoutBtn: {
    borderWidth: 1.2,
    borderColor: '#EF4444',
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 30,
    backgroundColor: '#FEF2F2',
  },
  logoutBtnText: {
    color: '#DC2626',
    fontWeight: '800',
    fontSize: 13,
  },
});
